
kind: Namespace
apiVersion: v1
metadata:
  name: sparkjava
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkjava
  labels:
    app: sparkjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkjava
  template:
    metadata:
      labels:
        app: sparkjava
    spec:
      containers:
      - name: sparkjava
        image: tftest/sparkjava
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sparkjava
spec:
  selector:
    app: sparkjava
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
